version: "3"
services:

#########################
# SERVERS               #
#########################
  fw-nginx:
    image: nginx
    volumes:
      - ../../dist:/usr/share/nginx/html
    ports:
      - 8080:80
    #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  fw-nexus:
    image: sonatype/nexus3
    volumes:
      - ../../nexus-data:/nexus-data
    ports:
      - 8081:8081
      - 8051:8051
      - 8052:8052
  fw-squid:
    image: minimum2scp/squid
    ports:
      - 3128:3128
      - 3129:3129

